#!/bin/sh

#This was the default one from /usr/share/doc/live-build/examples/auto
#I will consider tweaking it later if necessary.

set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
